'use strict';
const $=id=>document.getElementById(id);let preference='balanced',catalog,jobId=null,pollTimer,configuredJob;
const names={toy:'Toy residual（快速驗證）',resnet18:'ResNet-18',resnet34:'ResNet-34',resnet50:'ResNet-50',vgg16:'VGG-16',vgg19:'VGG-19',alexnet:'AlexNet',mobilenet_v2:'MobileNetV2'};
async function api(path,options){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}
function drawPreferences(){for(const button of $('preferences').children)button.classList.toggle('active',button.dataset.value===preference);const w=catalog.preferences[preference];$('weights').textContent=`Energy ${w.energy.toFixed(2)} / Area ${w.area.toFixed(2)} / Latency ${w.latency.toFixed(2)}`}
function artifact(row,file){const folder=row.folder.replaceAll('\\','/');const suffix=folder.split('/'+jobId+'/')[1];if(!suffix)throw Error('結果路徑與工作 ID 不符');return '/artifacts/'+jobId+'/'+suffix+'/'+file}
function showLayout(row){$('visual').hidden=false;$('layout').src=artifact(row,'layout.html');$('diagram').href=artifact(row,'architecture.svg')}
function render(job){jobId=job.id;$('job_id').value=job.id;localStorage.setItem('hybrid-job',job.id);$('state').textContent={queued:'等待開始',running:'探索中',complete:'探索完成',failed:'執行失敗',interrupted:'前次執行中斷'}[job.state]||job.state;$('message').textContent=job.message+` · ${job.completed}/${job.total} trials · 工作 ${job.id}`;$('progress').max=job.total||1;$('progress').value=job.completed;$('run').disabled=['running','queued'].includes(job.state);$('results').replaceChildren();for(const row of job.rows||[]){const tr=document.createElement('tr');const m=row.metrics;const values=[row.architecture+' / '+(names[row.model]||row.model),row.within_limits?(row.all_targets_met===false?'未達軟目標':'估算符合'):m.feasible?'超嚴格上限':'不可行',m.latency_s==null?'—':(m.latency_s*1000).toFixed(3)+' ms',m.energy_j==null?'—':(m.energy_j*1000).toFixed(2)+' mJ',m.power_w==null?'—':m.power_w.toFixed(3)+' W',m.area_mm2==null?'—':m.area_mm2.toFixed(2)+' mm²'];for(const [i,value]of values.entries()){const td=document.createElement('td');td.textContent=value;if(i===1)td.className=row.within_limits&&row.all_targets_met!==false?'good':'bad';tr.append(td)}const td=document.createElement('td');if(m.feasible){const button=document.createElement('button');button.textContent='查看布局';button.onclick=()=>showLayout(row);td.append(button)}else{td.className='detail';td.textContent=row.error||(m.violations||[]).join('; ')}tr.append(td);$('results').append(tr)}if(job.result){const result=job.result;const best=result.best_architecture;const selected=result.recommended_architecture||best;$('winner').className=best?'winner':'winner warning';const gaps=(result.constraint_reports||[]).flatMap(report=>report.limits.filter(limit=>!limit.within_target).map(limit=>`${names[report.model]||report.model} / ${({power_w:'平均功率',area_mm2:'總矽面積',latency_s:'延遲'})[limit.metric]||limit.metric}: 超出 ${limit.excess_percent==null?'未知':limit.excess_percent.toFixed(2)}% (${limit.strict?'嚴格上限':'軟目標'})`));$('winner').textContent=(best?`估算符合全部所選模型的嚴格限制：${best}。`:selected?`此次探索未找到符合嚴格限制的方案；最接近選項：${selected}。`:'沒有通過容量／資源檢查的候選。')+(gaps.length?' 差距：'+gaps.join('；'):'')+' 此結果是未校準的分析估算，非實體晶片限制保證。';if(selected&&!$('layout').getAttribute('src'))showLayout(job.rows.find(row=>row.architecture===selected&&row.metrics.feasible))}if(['running','queued'].includes(job.state)){clearTimeout(pollTimer);pollTimer=setTimeout(poll,5000)}}
function applyConfig(cfg){if(!cfg)return;preference=cfg.preference;drawPreferences();for(const el of document.querySelectorAll('#models input'))el.checked=cfg.models.includes(el.value);$('dies').value=cfg.dies.length>1?'all':String(cfg.dies[0]);$('noc').value=cfg.noc.length>1?'all':cfg.noc[0];$('ub').value=String(cfg.ub_mib);$('prefetch').value=String(cfg.prefetch_slots);for(const key of ['batch','budget','seed','dataflow'])$(key).value=cfg[key];for(const [name,key]of [['power','max_power'],['area','max_area'],['latency','max_latency_ms']]){$(name+'_on').checked=cfg[key]!=null;$(name+'_strict').checked=cfg['strict_'+name]!==false;if(cfg[key]!=null)$(name).value=cfg[key]}}
async function poll(){try{const job=await api('/api/jobs/'+jobId);if(configuredJob!==job.id){applyConfig(job.config);configuredJob=job.id}render(job)}catch(error){$('error').textContent=error.message;$('run').disabled=false}}
$('config').onsubmit=async event=>{event.preventDefault();$('error').textContent='';clearTimeout(pollTimer);try{const config={models:[...document.querySelectorAll('#models input:checked')].map(el=>el.value),preference,batch:Number($('batch').value),budget:Number($('budget').value),seed:Number($('seed').value),dies:$('dies').value==='all'?[4,8,16]:[Number($('dies').value)],noc:$('noc').value==='all'?['multi_ring','mesh']:[$('noc').value],ub_mib:Number($('ub').value),prefetch_slots:Number($('prefetch').value),dataflow:$('dataflow').value,planner:'traffic_dp',strict_power:$('power_strict').checked,strict_area:$('area_strict').checked,strict_latency:$('latency_strict').checked,max_power:$('power_on').checked?Number($('power').value):null,max_area:$('area_on').checked?Number($('area').value):null,max_latency_ms:$('latency_on').checked?Number($('latency').value):null};$('run').disabled=true;const response=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json','X-Hybrid-Request':'1'},body:JSON.stringify(config)});jobId=response.id;$('layout').removeAttribute('src');$('visual').hidden=true;$('winner').textContent='';await poll()}catch(error){$('error').textContent=error.message;$('run').disabled=false}};
$('restore').onsubmit=event=>{event.preventDefault();const id=$('job_id').value.trim();if(!/^[0-9a-f]{12}$/.test(id)){ $('error').textContent='工作 ID 必須是 12 位十六進位字串';return}jobId=id;$('layout').removeAttribute('src');poll()};
async function init(){catalog=await api('/api/catalog');for(const[value,item]of Object.entries(catalog.preferences)){const button=document.createElement('button');button.type='button';button.dataset.value=value;button.textContent=item.label;button.onclick=()=>{preference=value;drawPreferences()};$('preferences').append(button)}for(const model of catalog.models){const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.value=model;input.checked=['resnet18','vgg16'].includes(model);label.append(input,document.createTextNode(names[model]||model));$('models').append(label)}drawPreferences();const saved=localStorage.getItem('hybrid-job');if(saved){jobId=saved;poll()}}
init().catch(error=>$('error').textContent=error.message);
